ROOT = ../../

SRC = adc.c cpu.c flash.c i2c.c mpu.c ssi.c timer.c usb.c can.c epi.c gpio.c \
      i2s.c pwm.c sysctl.c uart.c watchdog.c comp.c ethernet.c hibernate.c \
      interrupt.c qei.c systick.c udma.c
TARGET = libdriver.a

include $(ROOT)/build/make.rules
