################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.c \
../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.o \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.d \
./App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/%.o: ../App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


