################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
obj/Source \
obj/Source/portable/MemMang \
obj/Source/portable/GCC/ARM_CM4F \
obj/App/STM32F4-Discovery/startup \
obj/App/STM32F4-Discovery \
obj/App/STM32F4-Discovery/board \
obj/App/STM32F4-Discovery/Libraries/STM32F4xx_StdPeriph_Driver/src \
obj/App/Common/Minimal \
Source \
Source/portable/MemMang \
Source/portable/GCC/ARM_CM4F \
App/STM32F4-Discovery \
App/STM32F4-Discovery/startup \
App/STM32F4-Discovery/board \
App/STM32F4-Discovery/Libraries/STM32_USB_OTG_Driver/src \
App/STM32F4-Discovery/Libraries/STM32_USB_HOST_Library/Core/src \
App/STM32F4-Discovery/Libraries/STM32_USB_HOST_Library/Class/MSC/src \
App/STM32F4-Discovery/Libraries/STM32_USB_HOST_Library/Class/HID/src \
App/STM32F4-Discovery/Libraries/STM32_USB_Device_Library/Core/src \
App/STM32F4-Discovery/Libraries/STM32_USB_Device_Library/Class/msc/src \
App/STM32F4-Discovery/Libraries/STM32_USB_Device_Library/Class/hid/src \
App/STM32F4-Discovery/Libraries/STM32_USB_Device_Library/Class/dfu/src \
App/STM32F4-Discovery/Libraries/STM32_USB_Device_Library/Class/cdc/src \
App/STM32F4-Discovery/Libraries/STM32_USB_Device_Library/Class/audio/src \
App/STM32F4-Discovery/Libraries/STM32F4xx_StdPeriph_Driver/src \
App/STM32F4-Discovery/Libraries/CMSIS/ST/STM32F4xx/Source/Templates \
App/STM32F4-Discovery/Libraries/CMSIS/ST/STM32F4xx/Source/Templates/TASKING \
App/STM32F4-Discovery/Libraries/CMSIS/Device/ST/STM32F4xx/Source/Templates \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/TransformFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/SupportFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/StatisticsFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/MatrixFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FilteringFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/FastMathFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/ControllerFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/ComplexMathFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/CommonTables \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_variance_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_sin_cos_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_signal_converge_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_matrix_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_linear_interp_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_graphic_equalizer_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_fir_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_fft_bin_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_dotproduct_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_convolution_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/arm_class_marks_example \
App/STM32F4-Discovery/Libraries/CMSIS/DSP_Lib/Examples/Common/Source \
App/Common/ethernet/uIP/uip-1.0/uip \
App/Common/ethernet/uIP/uip-1.0/apps/webserver \
App/Common/ethernet/lwip-1.4.0/src/netif \
App/Common/ethernet/lwip-1.4.0/src/netif/ppp \
App/Common/ethernet/lwip-1.4.0/src/core \
App/Common/ethernet/lwip-1.4.0/src/core/snmp \
App/Common/ethernet/lwip-1.4.0/src/core/ipv6 \
App/Common/ethernet/lwip-1.4.0/src/core/ipv4 \
App/Common/ethernet/lwip-1.4.0/src/api \
App/Common/ethernet/lwip-1.4.0/ports/win32 \
App/Common/ethernet/lwip-1.4.0/ports/win32/WinPCap \
App/Common/ethernet/lwip-1.4.0/ports/MicroBlaze-Ethernet-Lite \
App/Common/ethernet/lwIP_132/src/netif \
App/Common/ethernet/lwIP_132/src/netif/ppp \
App/Common/ethernet/lwIP_132/src/core \
App/Common/ethernet/lwIP_132/src/core/snmp \
App/Common/ethernet/lwIP_132/src/core/ipv6 \
App/Common/ethernet/lwIP_132/src/core/ipv4 \
App/Common/ethernet/lwIP_132/src/api \
App/Common/ethernet/lwIP_130/src/netif \
App/Common/ethernet/lwIP_130/src/netif/ppp \
App/Common/ethernet/lwIP_130/src/core \
App/Common/ethernet/lwIP_130/src/core/snmp \
App/Common/ethernet/lwIP_130/src/core/ipv6 \
App/Common/ethernet/lwIP_130/src/core/ipv4 \
App/Common/ethernet/lwIP_130/src/api \
App/Common/ethernet/lwIP_130/contrib/port/FreeRTOS \
App/Common/ethernet/lwIP_130/contrib/port/FreeRTOS/ColdFire \
App/Common/ethernet/lwIP/netif \
App/Common/ethernet/lwIP/netif/ppp \
App/Common/ethernet/lwIP/core \
App/Common/ethernet/lwIP/core/snmp \
App/Common/ethernet/lwIP/core/ipv4 \
App/Common/ethernet/lwIP/api \
App/Common/ethernet/FreeTCPIP \
App/Common/ethernet/FreeTCPIP/apps/httpd \
App/Common/ethernet/FreeRTOS-uIP \
App/Common/drivers/ST/STM32F10xFWLib/src \
App/Common/drivers/LuminaryMicro \
App/Common/drivers/Atmel/at91lib/utility \
App/Common/drivers/Atmel/at91lib/peripherals/usart \
App/Common/drivers/Atmel/at91lib/peripherals/twi \
App/Common/drivers/Atmel/at91lib/peripherals/tdes \
App/Common/drivers/Atmel/at91lib/peripherals/tc \
App/Common/drivers/Atmel/at91lib/peripherals/supc \
App/Common/drivers/Atmel/at91lib/peripherals/ssc \
App/Common/drivers/Atmel/at91lib/peripherals/spi \
App/Common/drivers/Atmel/at91lib/peripherals/slcdc \
App/Common/drivers/Atmel/at91lib/peripherals/rtt \
App/Common/drivers/Atmel/at91lib/peripherals/rtc \
App/Common/drivers/Atmel/at91lib/peripherals/rstc \
App/Common/drivers/Atmel/at91lib/peripherals/pwmc \
App/Common/drivers/Atmel/at91lib/peripherals/pmc \
App/Common/drivers/Atmel/at91lib/peripherals/pit \
App/Common/drivers/Atmel/at91lib/peripherals/pio \
App/Common/drivers/Atmel/at91lib/peripherals/mci \
App/Common/drivers/Atmel/at91lib/peripherals/lcd \
App/Common/drivers/Atmel/at91lib/peripherals/emac \
App/Common/drivers/Atmel/at91lib/peripherals/efc \
App/Common/drivers/Atmel/at91lib/peripherals/eefc \
App/Common/drivers/Atmel/at91lib/peripherals/dbgu \
App/Common/drivers/Atmel/at91lib/peripherals/can \
App/Common/drivers/Atmel/at91lib/peripherals/aic \
App/Common/drivers/Atmel/at91lib/peripherals/aes \
App/Common/drivers/Atmel/at91lib/peripherals/ac97c \
App/Common/drivers/Atmel/at91lib/boards/at91sam9xe-ek \
App/Common/Minimal \
App/Common/Full \

